// Action Types
export enum ActionType {
  LOGIN_WAIT = "LOGIN_WAIT",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  PROFILE_SUCCESS = "PROFILE_SUCCESS",
  PROFILE_FAILED = "PROFILE_FAILED",
}
